# Configuration for generating release notes
changelog:
  categories:
    - title: 'New Features'
      labels:
        - 'feature'
    - title: 'Bug Fixes'
      labels:
        - 'bug'
    - title: 'Improvements'
      labels:
        - 'enhancement'
    - title: 'Documentation'
      labels:
        - 'docs'
